version: '3'

services:
  web:
    image: ${DOCKER_REGISTRY}web
    build:
      context: .
      dockerfile: Web/Dockerfile

  api:
    image: ${DOCKER_REGISTRY}api
    build:
      context: .
      dockerfile: Api/Dockerfile
